# Generated by Django 3.0.8 on 2020-09-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200911_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('City', models.CharField(default='', max_length=60)),
                ('Call', models.IntegerField(default=0, max_length=14)),
                ('desc', models.CharField(max_length=1100)),
                ('State', models.CharField(max_length=50)),
                ('Zip', models.IntegerField(default=0, max_length=14)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
